import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Link from 'next/link'

const Home: NextPage= (_Studio) => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      

  
    </div>
  )
}
<Link href={''}>href="/Studio</Link>
export default Home
<!doctype html>
<html>
<head>
<title>Example</title>
</head>
<body style="background-color:yellowgreen;color:white;">
...content goes here...
</body>
</html>
